#!/bin/bash
VERSION="0.1";
THIS=${BASH_SOURCE##*/};
D=`echo ${BASH_SOURCE%/*}`; if [ $D = "" ];then D="."; fi

samtools_version=`samtools 2>&1 | perl -ne 'if($_=~/Version: ([\d|\.]+)/){ print $1,"\n";}'`
bedtools_version=`bedtools --version | perl -ne 'if($_=~/v([\d|\.]+)/){ print $1;}'`

point(){ 
	$D/pa_point.sh $@;
}

sum(){
	$D/bed_sum.sh $@;
}
filter(){
	$D/pa_filter.sh $@
}
cluster(){
	$D/pa_cluster.sh "$@"
}
report(){
	$D/pa_report.sh "$@"
}
comp(){
	$D/pa_compare.sh "$@"
}
anno(){
	$D/pa_anno.sh "$@"
}
data(){
	pa_data.sh "$@"
}

if [ $# -eq 0 ]; then
echo "
TOOL  : PolyA Analysis Tools @ BED BASH & BEYOND (v$VERSION)
AUTHOR: Hyunmin Kim (Hyeonmin.gim@gmail.com)
USAGE : 
	pa data     : list available datasets
	pa point	: find clevage sites
	pa filter	: filter out inter-primed artifacts 
	pa cluster	: cluster proximate points 
	pa comp     : compare clusters
	pa report	: report statistics
	pa anno     : gene annotation tools 
	pa sum		: merge read counts
" >&2
echo "	Checking existing tools:" >&2;
if [ $samtools_version ];then
	echo "	samtools $samtools_version detected" >&2;
	echo "  please update if $samtools_version < 1.1" >&2; 
	bedtools 2.22.0 detected

else
	echo "	please install samtools">&2; exit 1;
fi
if [ $bedtools_version ];then
	echo "	bedtools $bedtools_version detected" >&2;
	echo "  please update $bedtools_version < 2.22.0" >&2;
else
	echo "	please install bedtools" >&2; exit 1;
fi

fi
if [ $# -gt 0 ]; then
	eval "$@"
fi
